[package]
name = "brakwm-opt-jt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Jump threading pass for BrakWM"

[dependencies]
brakwm-core = { path = "../brakwm-core" }
brakwm-ir-lir = { path = "../brakwm-ir-lir" }
brakwm-opt-traits = { path = "../brakwm-opt-traits" }