[package]
name = "brakwm-bitcode"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "BrakWM bitcode serialization/deserialization (AST/HIR/MIR/LIR)"

[dependencies]
brakwm-core = { path = "../brakwm-core" }
brakwm-ir-ast = { path = "../brakwm-ir-ast" }
brakwm-ir-hir = { path = "../brakwm-ir-hir" }
brakwm-ir-mir = { path = "../brakwm-ir-mir" }
brakwm-ir-lir = { path = "../brakwm-ir-lir" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
brakwm-test = { path = "../brakwm-test" }