[package]
name = "brakwm-codegen-wat"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "LIR -> WAT text codegen (BrakWM WASM text backend)"

[dependencies]
brakwm-core = { path = "../brakwm-core" }
brakwm-ir-lir = { path = "../brakwm-ir-lir" }
brakwm-codegen-traits = { path = "../brakwm-codegen-traits" }

[dev-dependencies]
brakwm-frontend = { path = "../brakwm-frontend" }
brakwm-ir-hir = { path = "../brakwm-ir-hir" }
brakwm-ir-mir = { path = "../brakwm-ir-mir" }